### ISSUE TITLE
Bug when using custom encoding

### ISSUE THREAD

**Issue by Kacarott** [codewars/lambda-calculus#68]
Currently on line `150` there is a bare `numEncoding` used, which should be `config.numEncoding`

**Comment by JohanWiltink** [comment]
Looks like I forgot that one.

We also need tests for that then.

**Comment by JohanWiltink** [comment]
Still need tests.

**Comment by JohanWiltink** [comment]
`negabinary-scott-test` uses `Custom` encoding.
