### ISSUE TITLE
Numbers passed in as compiled LC parameters are treated as LC numerals

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/lambda-calculus#82]
When I use `numEncoding: "Church"` and define something like `zero = 0`, calling the compiled term with numbers will cause all kinds of unexpected results because LC automatically forces it to become a LC numeral.

This is *extremely* unexpected and very dangerous because it means numbers cannot be used as input arguments in JS side: I'd expect `zero(x => x + 1)(0)` to behave like a simple Church numeral to number operation, but no, the `0` is treated as an LC numeral here. The only workaround is to put `false`/`true` as argument, which limits to input value to only `0` and `1`:

```
zero(10)(10)(2)(x => x + 1)(false)
```

is actually `2 ^ (10 ^ (10 ^ 0)) = 1024`.

Negative and non-integral values are treated as LC numerals too, which naturally causes errors:

```
zero(0.5)(x => x + 1)(0)
RangeError: Invalid array length
    at fromInt (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:106:36)
    at result (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:327:60)
    at Context.<anonymous> (file:///workspace/test.js:8:17)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by Kacarott** [comment]
Numbers being implicitly converted to LC terms was a design decision, to allow tests for most katas to written far more easily. (consider `toInt(becomeImmortal(8)(5)(1)(100))` vs. `becomeImmortal(fromInt(8))(fromInt(5))(fromInt(1))(fromInt(100))(x=>x+1)(0)`).

It is expected that the vast majority of katas will use Church/Scott/BinaryScott, and for these, the `lambda-calculus` module provides `toInt`. Additionally for assertions, `assert.numEql` will implicitly convert its arguments (if they are LC terms) to numbers, meaning one could simply write `assert.numEql(zero, 0)`.

With that said, I do understand that working with numbers in LC terms can be unexpected and difficult, when that is needed. Internally for `toInt` we use a wrapper function `Primitive` to pass literal numbers to terms, without them being converted. Currently that is not exported by the module, but it could be.

Other workarounds, however, are to use either BigInt literals, or strings. Both `zero(x=>x+1n)(0n)` and `zero(x=>x+1)("0")` work.

**Comment by Voileexperiments** [comment]
There are three things being mixed up with this:

1. Calling LC term with LC term
2. Calling LC term with a value
3. Actually evaluating the term

In terms of Haskell you're doing something like (adapted from my SKI kata)

```haskell
data LC :: * -> * where
  -- 1
  Ap :: LC (a -> b) -> LC a -> LC b
  -- 2
  Var :: a -> LC a

-- 3
evalLC :: LC a -> a
evalLC = ...
```

Currently 1 and 2 are mixed together because some types of values are being implicitly, *forcefully* lifted. JS numbers cannot be used a parameter as a result. Since LC is an untyped language, it is especially important that the language should NOT modify what user passed in, or else the language becomes part of the problem itself.

(In another note, 1 and 3 are also mixed together, but that belongs to another issue.)

> to allow tests for most katas to written far more easily

A standalone language's aim should be to make that language self-consistent and easier to use by itself, not to make the language easy to use at the calling site where the interpreter implementation is written on.

> Other workarounds, however, are to use either BigInt literals, or strings. Both `zero(x=>x+1n)(0n)` and `zero(x=>x+1)("0")` work.

These are invalid workarounds too: the input are now big integers and strings instead of actual JS numbers (floats).

**Comment by JohanWiltink** [comment]
`Number`s are part of the language. This was a design decision and is not going to be changed.

If you're passing in a `Number`, it's going to be treated as an LC number. Future versions may make `Primitive` available to make passing unencoded numbers possible, but it is not a priority.

Closing.
