### ISSUE TITLE
Applying two LC terms is not completely lazy

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/lambda-calculus#84]
Applying two LC terms together is not completely lazy. With `numEncoding: "Church"`, `zero = 0` and something like `zero(10)(10)(10)(10)(10)(10)` (which would be `10 ^ 10 ^ 10 ^ 10 ^ 10`) the code will time out even though the term is not evaluated yet.

**Comment by JohanWiltink** [comment]
```lambdacalc
zero = 0
value = zero(10)(10)(10)(10)(10)(10)
multiply = \ m n f x . n (m f) x
```

Testing this code for `multiply` does not time out.

Yes, testing this code for `value`, in JS, times out. You can't usefully test anything with it, so there is no problem. Number definitions by themselves are not very useful, they only acquire meaning when a value is assigned, they are used to iterate something, or similar. Anything useful requires evaluating the number.

This specific behaviour was a design decision and is not going to be changed. It's also not a problem in kata practice.

Closing.
