### ISSUE TITLE
Allow for line continuation

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/lambda-calculus#86]
AFAIK currently all functions in LC has to be written in one line, which is very problematic when the function body becomes big. There are no ways to break down a function definition into multiple lines.

Since `\` is already used as lambda, maybe something else to denote line continuation?

**Comment by JohanWiltink** [comment]
> A definition starts with non-whitespace, non-comment text at the left margin and continues until ( not including ) the next non-whitespace, non-comment text _at the left margin,_ or until the end of the source file.

Indented lines continue the current definition.

**Comment by JohanWiltink** [comment]
E.g. this code ( from `binary-scott-number.lc` )

```lambdacalc
compare = \ m n . m (n EQ (K LT) (K LT))
                    ( \ zm . n GT (compare zm) ( \ zn . compare zm zn LT LT GT ) )
                    ( \ zm . n GT ( \ zn . compare zm zn LT GT GT ) (compare zm) )
```

is a single definition over multiple lines.

In practice, the restriction that continuing lines have to be indented is not a problem in our experience.

The Syntax Guide could probably do with an example.

**Comment by Voileexperiments** [comment]
Yeah, I didn't see any examples there.
